[package]
name = "rdla"
version = "0.2.2"
authors = ["Moritz Moeller <virtualritz@gmail.com>"]
edition = "2018"

[dependencies]
clap = { version = "2.33.0", features = ["yaml"] }
error-chain = "0.12.2"
if_chain = "1.0.0"
indicatif = "0.14.0"
nalgebra = "0.21.0"
nsi = "0.1.16"
ply-rs = "0.1.2"
rstar = "0.7.1"
rand_distr = "0.2.2"
rand_xoshiro = "0.4.0"
rand = "0.7.3"
serde = "1.0.110"
serde_derive = "1.0.110"
toml = "0.5.6"
tobj = "2.0.0"

#[target.'cfg(target_os = "macos")'.dependencies]
#jemallocator = "0.3.2"
[profile.release]
lto = "on"
opt-level = 3
panic = "unwind"
