[package]
name = "rdla"
version = "0.1.0"
authors = ["Moritz Moeller <virtualritz@gmail.com>"]
edition = "2018"

[dependencies]
clap = "*"
error-chain = "*"
if_chain = "*"
indicatif = "*"
nalgebra = "*"
nsi = { path="../crates/nsi/" }
ply-rs = "*"
rstar = "*"
random-fast-rng = "*"
rand = "*"
serde = "*"
serde_derive = "*"
toml = "*"
tobj = "*"


[profile.release]
lto = "on"
opt-level = 3
